profiles:
  - name: p1
    scope: 0
    freq: 10
  - name: p2
    scope: 1
    freq: 15
  - name: p3
    scope: 10
    freq: 2
seeds:
  - url: "http://www.nb.no"
    profiles:
      - p1
  - url: "https://a@www.nb.no:888/a"
    profiles:
      - p2
  - url: "http://www.vg.no"
    profiles:
      - p3
hostaliases:
  - name: kommuner
    hosts:
      - rana.kommune.no
      - vefsn.kommune.no
      - nesna.kommune.no
